Repository Foodlier/zb-foodlier, pull requests merged in 2023-09, with the labels that each got.

#53 Feature/be/security
  src/main/java/com/zerobase/foodlier/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/foodlier/common/security/provider/JwtTokenProvider.java
  src/main/java/com/zerobase/foodlier/common/security/provider/constants/TokenExpiredConstant.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/SignInForm.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/common/security/provider/JwtTokenProviderTest.java
Labels: 2-High

#56 Feature/fe/common
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/constants/Styles.tsx
  frontend/src/main.tsx
  frontend/src/mocks/dummy.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/worker.ts
  frontend/src/reset.css
Labels: 0-Low

#54 회원 가입 테스트 코드 작성 PR
  src/main/java/com/zerobase/foodlier/common/resttemplate/config/RestTemplateConfig.java
  src/main/java/com/zerobase/foodlier/global/member/regiser/facade/MemberRegisterFacade.java
  src/main/java/com/zerobase/foodlier/module/member/member/local/exception/LocalErrorCode.java
  src/main/java/com/zerobase/foodlier/module/member/member/local/service/LocalServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/member/regiser/facade/MemberRegisterFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/local/service/LocalServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: 1-Medium

#58 Feature/be/login
  src/test/java/com/zerobase/foodlier/global/profile/facade/ProfileFacadeTest.java
Labels: test

#63 Test: 로그인, 로그아웃, 회원정보 조회, 수정 테스트 작성
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: test

#73 요리사 등록 및 요리사 소개 수정 PR
  build.gradle
  src/main/java/com/zerobase/foodlier/global/profile/controller/profileController.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/ChefIntroduceForm.java
  src/main/java/com/zerobase/foodlier/module/member/chef/exception/ChefMemberErrorCode.java
  src/main/java/com/zerobase/foodlier/module/member/chef/exception/ChefMemberException.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberService.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/type/GradeType.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepository.java
Labels: 2-High

#74 Feature/be/request
  build.gradle
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/global/refrigerator/facade/RefrigeratorFacade.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomService.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/MemberRegisterDto.java
  src/main/java/com/zerobase/foodlier/module/request/exception/RequestErrorCode.java
  src/main/java/com/zerobase/foodlier/module/request/service/ReqeustService.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestService.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestServiceImpl.java
Labels: 0-Low

#76 요리사 등록 및 정보 수정 테스트 코드 작성
  src/test/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImplTest.java
Labels: 2-High

#79 Feature/be/recipe s3 이미지 등록, 삭제 테스트코드 작성
  src/main/java/com/zerobase/foodlier/common/s3/exception/S3ErrorCode.java
  src/main/java/com/zerobase/foodlier/common/s3/service/S3ServiceImpl.java
  src/test/java/com/zerobase/foodlier/common/s3/service/S3ServiceImplTest.java
Labels: test

#81 !HOTFIX: RequestForm Entity추가 및 연관관계 일부 수정
  src/main/java/com/zerobase/foodlier/module/dm/room/domain/model/DmRoom.java
  src/main/java/com/zerobase/foodlier/module/requestform/domain/model/RequestForm.java
  src/main/java/com/zerobase/foodlier/module/requestform/exception/RequestFormErrorCode.java
  src/main/java/com/zerobase/foodlier/module/requestform/exception/RequestFormException.java
  src/main/java/com/zerobase/foodlier/module/requestform/repository/RequestFormRepository.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormService.java
Labels: 3-Critical

#83 Feature/be/request fix
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/global/refrigerator/facade/RefrigeratorFacade.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomService.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/request/domain/model/Request.java
  src/main/java/com/zerobase/foodlier/module/request/domain/vo/Ingredient.java
  src/main/java/com/zerobase/foodlier/module/request/exception/RequestErrorCode.java
  src/main/java/com/zerobase/foodlier/module/request/repository/RequestRepository.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestService.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestServiceImpl.java
Labels: 2-High

#86 수정된 요청 보내기/취소, 수락/거절 로직에 대한 서비스단 테스트코드
  src/main/java/com/zerobase/foodlier/module/request/domain/model/Request.java
  src/main/java/com/zerobase/foodlier/module/request/exception/RequestErrorCode.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/requestform/domain/model/RequestForm.java
  src/test/java/com/zerobase/foodlier/module/request/service/RequestServiceImplTest.java
Labels: 1-Medium

#88 RefrigeratorFacade 테스트 코드 작성
  src/test/java/com/zerobase/foodlier/global/refrigerator/facade/RefrigeratorFacadeTest.java
Labels: 1-Medium

#89 Feature/be/request form 요청서 CRUD 작성
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/module/recipe/exception/RecipeErrorCode.java
  src/main/java/com/zerobase/foodlier/module/request/domain/vo/Ingredient.java
  src/main/java/com/zerobase/foodlier/module/requestform/domain/model/RequestForm.java
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormDetailDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormResponseDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/exception/RequestFormErrorCode.java
  src/main/java/com/zerobase/foodlier/module/requestform/repository/RequestFormRepository.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormService.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormServiceImpl.java
Labels: 1-Medium

#90 Feature/fe/login
  frontend/src/mocks/dummy.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RegisterPage.tsx
  frontend/src/styles/RegisterPage.styled.ts
Labels: 1-Medium
