Repository Foodlier/zb-foodlier, pull requests merged in 2023-10, with the labels that each got.

#91 요리사 조회하기 기능 구현 PR
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/AroundChefDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/RequestedChefDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberService.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/type/ChefSearchType.java
Labels: 1-Medium

#95 1:1 채팅 UI
  frontend/src/App.tsx
  frontend/src/components/BottomNavigation.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/ProposalModal.tsx
  frontend/src/components/chat/RoomListItem.tsx
  frontend/src/components/recipe/RecipeItem.tsx
  frontend/src/components/ui/ModalWithTwoButton.tsx
  frontend/src/hooks/useIcon.tsx
  frontend/src/pages/chat/ChattingPage.tsx
  frontend/src/pages/recipe/RecipePage.tsx
  frontend/src/styles/BottomNavigation.styled.ts
  frontend/src/styles/Header.styled.ts
  frontend/src/styles/chat/ChatRoom.styled.ts
  frontend/src/styles/chat/ChattingPage.styled.ts
  frontend/src/styles/chat/ProposalModal.styled.ts
  frontend/src/styles/chat/RoomListItem.styled.ts
  frontend/src/styles/recipe/RecipePage.styled.ts
  frontend/src/styles/ui/ModalWithTwoButton.styled.ts
  frontend/src/utils/getTime.tsx
  frontend/src/utils/returnPriceWithComma.tsx
Labels: 1-Medium

#92 BE - 주변요리사 조회 및 요청된 요리사 조회에 대한 테스트
  src/test/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImplTest.java
Labels: 0-Low

#96 FE- 꿀조합 상세페이지 UI 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/chef/ChefData.ts
  frontend/src/components/chef/ChefItem.tsx
  frontend/src/components/notification/NotificationItem.tsx
  frontend/src/components/recipe/detail/DetailIngredients.tsx
  frontend/src/components/recipe/detail/DetailMain.tsx
  frontend/src/components/recipe/detail/DetailProcedure.tsx
  frontend/src/components/search/MoSearch.tsx
  frontend/src/components/search/SearchBar.tsx
  frontend/src/components/search/WebSearch.tsx
  frontend/src/components/slider/Slide.ts
  frontend/src/components/slider/Slider.tsx
  frontend/src/components/slider/SliderCard.tsx
  frontend/src/components/ui/Button.tsx
  frontend/src/hooks/useIcon.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/recipe/RecipeDetailPage.tsx
  frontend/src/pages/recipe/RecipePage.tsx
  frontend/src/styles/BottomNavigation.styled.ts
  frontend/src/styles/MainPage.styled.ts
  frontend/src/styles/recipe/detail/DetailIngredients.styled.ts
  frontend/src/styles/recipe/detail/DetailMain.styled.ts
  frontend/src/styles/recipe/detail/DetailProcedure.styled.ts
Labels: 2-High

#94 BE -토스 페이 api를 통한 포인트 충전 및 충전 내역 생성
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
  src/main/java/com/zerobase/foodlier/global/point/controller/PointController.java
  src/main/java/com/zerobase/foodlier/module/history/charge/domain/model/PointChargeHistory.java
  src/main/java/com/zerobase/foodlier/module/payment/constants/PaymentConstants.java
  src/main/java/com/zerobase/foodlier/module/payment/domain/model/Payment.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentRequest.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponse.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponseHandleCancelDto.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponseHandleCardDto.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponseHandleDto.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponseHandleFailDto.java
  src/main/java/com/zerobase/foodlier/module/payment/exception/PaymentErrorCode.java
  src/main/java/com/zerobase/foodlier/module/payment/exception/PaymentException.java
  src/main/java/com/zerobase/foodlier/module/payment/repository/PaymentRepository.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentService.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/payment/type/OrderNameType.java
  src/main/java/com/zerobase/foodlier/module/payment/type/PayType.java
Labels: 0-Low

#106 BE - !HOTFIX 요청서 상세보기 기능 오류로 인한 dto 수정
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormDetailDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormResponseDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormServiceImpl.java
Labels: bug

#104 BE - payment 테스트 코드
  src/main/java/com/zerobase/foodlier/global/point/controller/PointController.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentRequest.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentService.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImplTest.java
Labels: test

#105 BE - redisson lock 구현
  src/main/java/com/zerobase/foodlier/common/aop/RedissonLock.java
  src/main/java/com/zerobase/foodlier/common/redisson/config/RedissonConfig.java
  src/main/java/com/zerobase/foodlier/common/redisson/exception/RedissonErrorCode.java
  src/main/java/com/zerobase/foodlier/common/redisson/exception/RedissonException.java
  src/main/java/com/zerobase/foodlier/common/redisson/service/RedissonLockAop.java
  src/main/java/com/zerobase/foodlier/common/redisson/service/RedissonLockService.java
  src/main/java/com/zerobase/foodlier/common/redisson/service/RedissonLockServiceImpl.java
Labels: 1-Medium

#108 BE - 요청 보내기 로직 긴급수정 [!HOTFIX]
  src/main/java/com/zerobase/foodlier/module/request/service/RequestServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/requestform/repository/RequestFormRepository.java
  src/test/java/com/zerobase/foodlier/module/request/service/RequestServiceImplTest.java
Labels: 3-Critical

#110 BE - 요청/주변 요리사 조회하기 누락된 값 추가 [!HOTFIX]
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/AroundChefDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/RequestedChefDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepository.java
  src/test/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImplTest.java
Labels: 3-Critical

#111 BE - 요청서 crud 테스트코드 작성, 요청서 로직 일부추가
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/requestForm/service/RequestFormServiceImplTest.java
Labels: test

#112 BE - 좋아요 누르기/취소
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/module/heart/domain/model/Heart.java
  src/main/java/com/zerobase/foodlier/module/heart/exception/HeartErrorCode.java
  src/main/java/com/zerobase/foodlier/module/heart/exception/HeartException.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepository.java
  src/main/java/com/zerobase/foodlier/module/heart/service/HeartService.java
  src/main/java/com/zerobase/foodlier/module/heart/service/HeartServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/domain/model/Recipe.java
Labels: 1-Medium

#119 BE - 요청서 상세보기 반환값 수정 및 관련 테스트코드 수정
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormDetailDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/requestForm/service/RequestFormServiceImplTest.java
Labels: 1-Medium

#115 BE - 견적서 CRUD 및 견적서 보내기
  src/main/java/com/zerobase/foodlier/global/quotation/controller/QuotationController.java
  src/main/java/com/zerobase/foodlier/global/quotation/facade/QuotationFacade.java
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/global/recipe/facade/RecipeFacade.java
  src/main/java/com/zerobase/foodlier/module/heart/service/HeartServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/quotation/QuotationDetailResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/quotation/QuotationDtoRequest.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/quotation/QuotationTopResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/ImageUrlDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDetailDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDtoRequest.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDtoResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeImageResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeIngredientDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/exception/quotation/QuotationErrorCode.java
  src/main/java/com/zerobase/foodlier/module/recipe/exception/quotation/QuotationException.java
  src/main/java/com/zerobase/foodlier/module/recipe/exception/recipe/RecipeErrorCode.java
  src/main/java/com/zerobase/foodlier/module/recipe/exception/recipe/RecipeException.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/request/exception/RequestErrorCode.java
  src/main/java/com/zerobase/foodlier/module/request/repository/RequestRepository.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestService.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/recipe/facade/RecipeFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
Labels: 1-Medium

#121 FE - 알림 테스트를 위한 작업 PR
  frontend/src/App.tsx
  frontend/src/components/Notification.tsx
Labels: 1-Medium

#123 BE - 알림 기능 구현
  src/main/java/com/zerobase/foodlier/common/aop/notification/annotation/Notification.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/aspect/NotificationAspect.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/dto/Notify.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/ActionType.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/NotifyMessage.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/NotifyUrl.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/PerformerType.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/SendType.java
  src/main/java/com/zerobase/foodlier/global/notification/controller/NotificationController.java
  src/main/java/com/zerobase/foodlier/global/notification/dto/NotificationRequestDto.java
  src/main/java/com/zerobase/foodlier/global/notification/facade/NotificationFacade.java
  src/main/java/com/zerobase/foodlier/module/notification/domain/model/Notification.java
  src/main/java/com/zerobase/foodlier/module/notification/domain/type/NotificationType.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/NotificationDto.java
  src/main/java/com/zerobase/foodlier/module/notification/exception/NotificationErrorCode.java
  src/main/java/com/zerobase/foodlier/module/notification/repository/NotificationRepository.java
  src/main/java/com/zerobase/foodlier/module/notification/repository/sse/EmitterRepository.java
  src/main/java/com/zerobase/foodlier/module/notification/repository/sse/EmitterRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/notification/service/NotificationService.java
  src/main/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterService.java
  src/main/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/notification/service/notification/NotificationService.java
  src/main/java/com/zerobase/foodlier/module/notification/service/notification/NotificationServiceImpl.java
Labels: 1-Medium

#124 BE - 견적서 CRUD 및 요청/레시피변환 로직 테스트
  src/test/java/com/zerobase/foodlier/global/quotation/facade/QuotationFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/requestForm/service/RequestFormServiceImplTest.java
Labels: test

#125 BE - 좋아요 누르기/취소 코드 및 테스트 코드
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/module/heart/domain/model/Heart.java
  src/main/java/com/zerobase/foodlier/module/heart/exception/HeartErrorCode.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepository.java
  src/main/java/com/zerobase/foodlier/module/heart/service/HeartService.java
  src/main/java/com/zerobase/foodlier/module/heart/service/HeartServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/heart/service/HeartServiceImplTest.java
Labels: 1-Medium

#135 Vercel 배포전 코드리뷰
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Notification.tsx
  frontend/src/components/chat/RoomListItem.tsx
  frontend/src/components/chef/ChefItem.tsx
  frontend/src/components/notification/NotificationItem.tsx
  frontend/src/components/recipe/RecipeImage.tsx
  frontend/src/components/recipe/RecipeItem.tsx
  frontend/src/components/recipe/detail/DetailIngredients.tsx
  frontend/src/components/recipe/detail/DetailMain.tsx
  frontend/src/components/recipe/detail/DetailProcedure.tsx
  frontend/src/components/search/MoSearch.tsx
  frontend/src/components/search/WebSearch.tsx
  frontend/src/components/slider/Slider.tsx
  frontend/src/components/slider/SliderCard.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/auth/LoginPage.tsx
  frontend/src/pages/auth/RegisterPage.tsx
  frontend/src/pages/recipe/RecipeDetailPage.tsx
Labels: 0-Low

#139 FE - sse 테스트 헤더 추가
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Notification.tsx
Labels: 1-Medium

#150 MSW 및 회원가입 구현 테스트
  frontend/.eslintrc.cjs
  frontend/src/components/auth/AddressModal.tsx
  frontend/src/main.tsx
  frontend/src/mocks/browsers.ts
  frontend/src/mocks/dummy.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/worker.ts
  frontend/src/pages/auth/RegisterPage.tsx
  frontend/src/styles/auth/RegisterPage.styled.ts
Labels: 2-High

#142 BE - 포인트 거래 및 내역 생성
  src/main/java/com/zerobase/foodlier/global/point/controller/PointController.java
  src/main/java/com/zerobase/foodlier/global/point/facade/TransactionFacade.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/domain/model/MemberBalanceHistory.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryService.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/type/PaymentType.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepository.java
  src/main/java/com/zerobase/foodlier/module/request/repository/RequestRepository.java
  src/main/java/com/zerobase/foodlier/module/transaction/dto/TransactionDto.java
  src/main/java/com/zerobase/foodlier/module/transaction/exception/TransactionErrorCode.java
  src/main/java/com/zerobase/foodlier/module/transaction/service/TransactionService.java
  src/main/java/com/zerobase/foodlier/module/transaction/service/TransactionServiceImpl.java
Labels: 0-Low

#143 BE - 주변 요청 조회하기
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/RequestedMemberDto.java
  src/main/java/com/zerobase/foodlier/module/member/member/exception/MemberErrorCode.java
  src/main/java/com/zerobase/foodlier/module/member/member/repository/MemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/type/RequestedOrderingType.java
Labels: 1-Medium

#145 BE - 알림 기능 수정
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/NotifyMessage.java
  src/main/java/com/zerobase/foodlier/global/notification/facade/NotificationFacade.java
  src/main/java/com/zerobase/foodlier/module/notification/exception/NotificationErrorCode.java
  src/main/java/com/zerobase/foodlier/module/notification/repository/notification/NotificationRepository.java
  src/main/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterService.java
  src/main/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/notification/service/notification/NotificationServiceImpl.java
Labels: 1-Medium

#146 BE - 꿀조합 후기 CRUD 테스트 코드 작성
  src/test/java/com/zerobase/foodlier/global/review/facade/RecipeReviewFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImplTest.java
Labels: 0-Low

#151 BE-!Hotfix 알림 기능 수정
  src/main/java/com/zerobase/foodlier/module/notification/dto/NotificationDto.java
Labels: 3-Critical

#148 BE - 요리사 후기 CR 로직
  src/main/java/com/zerobase/foodlier/global/profile/controller/profileController.java
  src/main/java/com/zerobase/foodlier/global/review/controller/ReviewController.java
  src/main/java/com/zerobase/foodlier/global/review/facade/ChefReviewFacade.java
  src/main/java/com/zerobase/foodlier/module/member/chef/domain/model/ChefMember.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberService.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/request/repository/RequestRepository.java
  src/main/java/com/zerobase/foodlier/module/review/chef/domain/model/ChefReview.java
  src/main/java/com/zerobase/foodlier/module/review/chef/dto/ChefReviewForm.java
  src/main/java/com/zerobase/foodlier/module/review/chef/dto/ChefReviewResponseDto.java
  src/main/java/com/zerobase/foodlier/module/review/chef/exception/ChefReviewErrorCode.java
  src/main/java/com/zerobase/foodlier/module/review/chef/repository/ChefReviewRepository.java
  src/main/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewService.java
  src/main/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewServiceImpl.java
Labels: 0-Low

#160 FE - z-index 변수 설정, 알림 테스트 코드 삭제
  frontend/src/App.tsx
  frontend/src/components/Notification.tsx
  frontend/src/constants/Styles.tsx
  frontend/src/styles/BottomNavigation.styled.ts
  frontend/src/styles/Header.styled.ts
  frontend/src/styles/auth/LoginPage.styled.ts
  frontend/src/styles/chat/ProposalModal.styled.ts
  frontend/src/styles/refrigerator/ListModal.styled.ts
  frontend/src/styles/search/MoSearch.styled.ts
  frontend/src/styles/search/SearchBar.styled.ts
  frontend/src/styles/ui/ModalWithTwoButton.styled.ts
Labels: 0-Low

#165 FE - 꿀조합 상세페이지 UI 구현
  frontend/src/App.tsx
  frontend/src/components/recipe/detail/comment/Comment.ts
  frontend/src/components/recipe/detail/comment/RecipeCommentForm.tsx
  frontend/src/components/recipe/detail/comment/RecipeCommentItem.tsx
  frontend/src/components/recipe/detail/comment/RecipeCommentItemActions.tsx
  frontend/src/components/recipe/detail/comment/RecipeCommentList.tsx
  frontend/src/components/recipe/detail/comment/allDummyComments.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewItem.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewList.tsx
  frontend/src/components/search/MoSearch.tsx
  frontend/src/components/search/WebSearch.tsx
  frontend/src/components/ui/Button.tsx
  frontend/src/components/ui/Dialog.tsx
  frontend/src/constants/Styles.tsx
  frontend/src/hooks/useIcon.tsx
  frontend/src/pages/recipe/RecipeDetailPage.tsx
  frontend/src/pages/recipe/WriteReviewPage.tsx
  frontend/src/reset.css
  frontend/src/styles/recipe/WriteReviewPage.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentForm.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentItem.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentList.styled.ts
  frontend/src/styles/recipe/detail/review/RecipeReviewItem.styled.ts
  frontend/src/styles/recipe/detail/review/RecipeReviewList.styled.ts
Labels: 1-Medium

#167 FE - build test 후 merge
  frontend/src/App.tsx
  frontend/src/components/recipe/detail/comment/Comment.ts
  frontend/src/components/recipe/detail/comment/RecipeCommentForm.tsx
  frontend/src/components/recipe/detail/comment/RecipeCommentItem.tsx
  frontend/src/components/recipe/detail/comment/RecipeCommentItemActions.tsx
  frontend/src/components/recipe/detail/comment/RecipeCommentList.tsx
  frontend/src/components/recipe/detail/comment/allDummyComments.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewItem.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewList.tsx
  frontend/src/components/search/MoSearch.tsx
  frontend/src/components/search/WebSearch.tsx
  frontend/src/components/ui/Button.tsx
  frontend/src/components/ui/Dialog.tsx
  frontend/src/constants/Styles.tsx
  frontend/src/hooks/useIcon.tsx
  frontend/src/pages/recipe/RecipeDetailPage.tsx
  frontend/src/pages/recipe/WriteReviewPage.tsx
  frontend/src/reset.css
  frontend/src/styles/recipe/WriteReviewPage.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentForm.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentItem.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentList.styled.ts
  frontend/src/styles/recipe/detail/review/RecipeReviewItem.styled.ts
  frontend/src/styles/recipe/detail/review/RecipeReviewList.styled.ts
Labels: 1-Medium

#168 FE - 회원가입 페이지 일부 수정
  frontend/src/pages/auth/RegisterPage.tsx
  frontend/src/styles/auth/RegisterPage.styled.ts
Labels: 1-Medium

#152 BE - 주변 요청 조회하기 테스트
  src/main/java/com/zerobase/foodlier/module/member/member/exception/MemberErrorCode.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: 0-Low

#153 BE - 포인트 거래 및 내역 생성 테스트 코드
  src/main/java/com/zerobase/foodlier/module/transaction/dto/SuggestionForm.java
  src/test/java/com/zerobase/foodlier/global/point/facade/TransactionFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/transaction/service/TransactionServiceImplTest.java
Labels: test

#154 BE - 포인트 충전 결제 로직 변경
  src/main/java/com/zerobase/foodlier/global/point/controller/PointController.java
  src/main/java/com/zerobase/foodlier/global/point/facade/PaymentFacade.java
  src/main/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryService.java
  src/main/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentService.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/point/facade/PaymentFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImplTest.java
Labels: 1-Medium

#155 BE - 요리사 후기 테스트 코드
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/review/facade/ChefReviewFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewServiceImplTest.java
Labels: 0-Low

#172 BE - 알림 전송 기능 테스트
  src/test/java/com/zerobase/foodlier/global/notification/facade/NotificationFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterServiceTest.java
  src/test/java/com/zerobase/foodlier/module/notification/service/notification/NotificationServiceTest.java
Labels: 1-Medium

#182 BE - 댓글 및 대댓글 기능 구현
  src/main/java/com/zerobase/foodlier/global/comment/controller/CommentController.java
  src/main/java/com/zerobase/foodlier/global/comment/facade/comment/CommentFacade.java
  src/main/java/com/zerobase/foodlier/global/comment/facade/reply/ReplyFacade.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/domain/model/Comment.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/dto/CommentDto.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/dto/CommentPagingDto.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/exception/CommentErrorCode.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentRepository.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/service/CommentService.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/service/CommentServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/domain/model/Reply.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/dto/ReplyDto.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/dto/ReplyPagingDto.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/exception/ReplyErrorCode.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplyRepository.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyService.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/domain/document/RecipeDocument.java
  src/main/java/com/zerobase/foodlier/module/recipe/domain/model/Recipe.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
Labels: 1-Medium

#181 BE - 충전 및 결제 내역 조회 및 테스트 코드
  src/main/java/com/zerobase/foodlier/global/point/controller/PointController.java
  src/main/java/com/zerobase/foodlier/module/history/charge/domain/model/PointChargeHistory.java
  src/main/java/com/zerobase/foodlier/module/history/charge/dto/PointChargeHistoryDto.java
  src/main/java/com/zerobase/foodlier/module/history/charge/repository/PointChargeHistoryRepository.java
  src/main/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryService.java
  src/main/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/domain/model/MemberBalanceHistory.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/dto/MemberBalanceHistoryDto.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/repository/MemberBalanceHistoryRepository.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryService.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/history/type/TransactionType.java
  src/main/java/com/zerobase/foodlier/module/payment/domain/model/Payment.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImplTest.java
Labels: 1-Medium, test

#183 BE - 비밀번호 변경
  src/main/java/com/zerobase/foodlier/global/profile/controller/profileController.java
  src/main/java/com/zerobase/foodlier/module/member/member/profile/dto/PasswordChangeForm.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
Labels: 0-Low

#184 BE - 채팅방 테스트코드 작성
  src/main/java/com/zerobase/foodlier/module/dm/dm/dto/MessagePubDto.java
  src/main/java/com/zerobase/foodlier/module/dm/room/dto/DmRoomDto.java
  src/test/java/com/zerobase/foodlier/module/dm/dm/service/DmServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/transaction/service/TransactionServiceImplTest.java
Labels: 2-High, test

#191 BE - ec2 배포와 관련된 설정 변경 및 기능 추가
  src/main/java/com/zerobase/foodlier/common/elasticsearch/config/ElasticSearchConfig.java
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
  src/main/java/com/zerobase/foodlier/common/server/controller/ServerProfileController.java
Labels: 3-Critical

#196 BE - !HOTFIX EC2배포를 위한 CORS 경로 추가 및 시큐리티 제외 경로 추가
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
Labels: 3-Critical

#198 FE - 레시피 API 연동
  frontend/src/components/recipe/detail/DetailIngredients.tsx
  frontend/src/components/recipe/detail/DetailMain.tsx
  frontend/src/components/recipe/detail/DetailProcedure.tsx
  frontend/src/components/recipe/detail/comment/RecipeCommentList.tsx
  frontend/src/components/ui/ModalWithoutButton.tsx
  frontend/src/constants/Data.tsx
  frontend/src/constants/Interfacs.tsx
  frontend/src/pages/recipe/RecipeDetailPage.tsx
  frontend/src/pages/recipe/WriteRecipePage.tsx
  frontend/src/pages/refrigerator/WriteQuotationPage.tsx
  frontend/src/styles/recipe/detail/DetailMain.styled.ts
  frontend/src/styles/recipe/detail/DetailProcedure.styled.ts
  frontend/src/styles/ui/ModalWithoutButton.styled.ts
  frontend/src/utils/FetchCall.tsx
  frontend/vite.config.ts
Labels: 1-Medium

#185 BE - 비밀번호 변경 테스트 코드
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: test

#188 BE - 요청에 대한 상세 조회 기능 구현
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/module/request/dto/RequestDetailDto.java
  src/main/java/com/zerobase/foodlier/module/request/exception/RequestErrorCode.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestService.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestServiceImpl.java
Labels: 0-Low

#190 BE - 등급 정의 및 등급 할당
  src/main/java/com/zerobase/foodlier/module/member/chef/domain/model/ChefMember.java
  src/main/java/com/zerobase/foodlier/module/member/chef/type/GradeType.java
Labels: 0-Low

#200 BE - 비밀번호 찾기 테스트 코드
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/member/password/facade/PasswordFindFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/mail/service/MailServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: test

#204 BE - !HOTFIX 리스트 응답 객체 정의 및 로직, 테스트 코드 수정
  src/main/java/com/zerobase/foodlier/common/response/ListResponse.java
  src/main/java/com/zerobase/foodlier/global/comment/controller/CommentController.java
  src/main/java/com/zerobase/foodlier/global/dm/controller/DmController.java
  src/main/java/com/zerobase/foodlier/global/notification/controller/NotificationController.java
  src/main/java/com/zerobase/foodlier/global/point/controller/PointController.java
  src/main/java/com/zerobase/foodlier/global/profile/controller/profileController.java
  src/main/java/com/zerobase/foodlier/global/quotation/controller/QuotationController.java
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/global/review/controller/ReviewController.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/dto/CommentPagingDto.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/service/CommentService.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/service/CommentServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/dto/ReplyPagingDto.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyService.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/dm/room/repository/DmRoomRepository.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomService.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryService.java
  src/main/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryService.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberService.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/notification/service/notification/NotificationService.java
  src/main/java/com/zerobase/foodlier/module/notification/service/notification/NotificationServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormService.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewService.java
  src/main/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewService.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/comment/comment/service/CommentServiceTest.java
  src/test/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyServiceTest.java
  src/test/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/notification/service/notification/NotificationServiceTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/requestForm/service/RequestFormServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImplTest.java
Labels: 2-High

#202 BE - 접속 토큰 재발급 로직 수정
  src/main/java/com/zerobase/foodlier/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/foodlier/common/security/provider/JwtTokenProvider.java
  src/main/java/com/zerobase/foodlier/global/auth/controller/AuthController.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/common/security/provider/JwtTokenProviderTest.java
Labels: 0-Low

#205 BE - 레시피 목록 가져오기
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeListDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/exception/recipe/RecipeErrorCode.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/OrderType.java
Labels: 0-Low

#206 BE - 접속 토큰 재발급 테스트
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: 0-Low

#207 BE - 회원 탈퇴 테스트 코드
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: test

#208 BE - 마이페이지 및 공개프로필 데이터 조회
  src/main/java/com/zerobase/foodlier/global/profile/controller/ProfileController.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/dto/MyPageCommentDto.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentRepository.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/service/CommentService.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/service/CommentServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/ChefProfileDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/TopChefDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberService.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/DefaultProfileDtoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/profile/dto/MemberPrivateProfileResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/repository/MemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDtoTopResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/dto/RecipeReviewResponseDto.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepository.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewService.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: 0-Low

#209 BE - 요청 상세 조회 테스트 코드
  src/test/java/com/zerobase/foodlier/module/request/service/RequestServiceImplTest.java
Labels: test

#211 BE - 도메인 회원가입 이미지 처리 방식 수정
  src/main/java/com/zerobase/foodlier/global/member/regiser/facade/MemberRegisterFacade.java
  src/main/java/com/zerobase/foodlier/module/member/member/domain/model/Member.java
  src/test/java/com/zerobase/foodlier/global/member/regiser/facade/MemberRegisterFacadeTest.java
Labels: 2-High

#212 BE - 메인페이지, 꿀조합 기본 조회, 오늘의 추천 레시피 테스트 + 레시피 상세 조회 좋아요 여부, 개인정보 수정 시 이미지값 처리
  src/main/java/com/zerobase/foodlier/global/profile/facade/ProfileFacade.java
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/module/recipe/domain/model/Recipe.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDtoResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeListDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/OrderType.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
Labels: 2-High, test

#216 FE - 회원가입 구현
  frontend/src/mocks/handlers.ts
  frontend/src/pages/auth/LoginPage.tsx
  frontend/src/pages/auth/RegisterPage.tsx
Labels: 2-High

#215 BE - Log Aop
  src/main/java/com/zerobase/foodlier/common/aop/log/LogAop.java
  src/main/resources/logback-spring.xml
Labels: 0-Low

#213 BE - 마이페이지 및 공개프로필 조회 테스트
  src/main/java/com/zerobase/foodlier/module/member/member/dto/DefaultProfileDtoResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDtoTopResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/comment/comment/service/CommentServiceTest.java
  src/test/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImplTest.java
Labels: 0-Low

#221 BE - 꿀조합 검색 필터 기능
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/module/recipe/domain/document/RecipeDocument.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeCardDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeSearchRequest.java
  src/main/java/com/zerobase/foodlier/module/recipe/exception/recipe/RecipeErrorCode.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeSearchRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/SearchType.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/SortType.java
  src/main/resources/elasticsearch/recipe-mapping.json
Labels: 1-Medium

#233 FE - CORS 정책 수정 및 회원가입 구현
  frontend/package.json
  frontend/src/pages/auth/RegisterPage.tsx
  frontend/src/setupProxy.js
  frontend/vite.config.ts
Labels: 2-High

#229 BE - 도메인 회원가입시 이메일 인증 코드 형식 변경
  src/main/java/com/zerobase/foodlier/global/member/mail/facade/EmailVerificationFacade.java
  src/main/java/com/zerobase/foodlier/module/member/member/mail/constants/GenerateCodeConstants.java
  src/main/java/com/zerobase/foodlier/module/member/member/mail/service/RandomCodeService.java
  src/main/java/com/zerobase/foodlier/module/member/member/mail/service/RandomCodeServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/member/mail/facade/EmailVerificationFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/mail/service/RandomCodeServiceImplTest.java
Labels: 0-Low

#224 BE - 네이버, 카카오 소셜 로그인 기능
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
  src/main/java/com/zerobase/foodlier/global/auth/controller/AuthController.java
  src/main/java/com/zerobase/foodlier/global/member/oAuth/facade/OAuthFacade.java
  src/main/java/com/zerobase/foodlier/global/request/controller/S3Controller.java
  src/main/java/com/zerobase/foodlier/global/request/dto/file
  src/main/java/com/zerobase/foodlier/module/member/member/client/KakaoApiClient.java
  src/main/java/com/zerobase/foodlier/module/member/member/client/NaverApiClient.java
  src/main/java/com/zerobase/foodlier/module/member/member/client/OAuthApiClient.java
  src/main/java/com/zerobase/foodlier/module/member/member/constants/OAuthConstants.java
  src/main/java/com/zerobase/foodlier/module/member/member/domain/model/Member.java
  src/main/java/com/zerobase/foodlier/module/member/member/exception/OAuthErrorCode.java
  src/main/java/com/zerobase/foodlier/module/member/member/exception/OAuthException.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/OAuthInfoService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/OAuthInfoServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/KakaoInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/KakaoLoginParams.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/KakaoTokens.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/NaverInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/NaverLoginParams.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/NaverTokens.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/OAuthInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/OAuthLoginParams.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/RequestBodyKakao.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/RequestBodyNaver.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/SocialLoginResponse.java
Labels: 0-Low

#226 BE - !HOTFIX: 로그에 오타 수정
  src/main/java/com/zerobase/foodlier/common/aop/log/LogAop.java
Labels: 3-Critical

#230 BE - 레시피 검색 필터 테스트
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
Labels: 1-Medium

#231 BE - 레시피 조회 수정
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
Labels: 2-High

#232 BE - 메세지 가져오기 시 개수 변경
  src/main/java/com/zerobase/foodlier/module/dm/dm/service/DmServiceImpl.java
Labels: 0-Low

#236 BE - queryDSL로 변경
  build.gradle
  src/main/java/com/zerobase/foodlier/common/jpa/config/QueryDslConfig.java
  src/main/java/com/zerobase/foodlier/common/jpa/dialect/MySQLCustomDialect.java
  src/main/java/com/zerobase/foodlier/module/dm/room/dto/DmRoomDto.java
  src/main/java/com/zerobase/foodlier/module/dm/room/repository/DmRoomRepository.java
  src/main/java/com/zerobase/foodlier/module/dm/room/repository/DmRoomRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/dm/room/repository/DmRoomRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepository.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/heart/service/HeartServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/AroundChefDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/dto/RequestedChefDto.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/DefaultProfileDtoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/RequestedMemberDto.java
  src/main/java/com/zerobase/foodlier/module/member/member/repository/MemberRepository.java
  src/main/java/com/zerobase/foodlier/module/member/member/repository/MemberRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/member/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/quotation/QuotationTopResponse.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/request/repository/RequestRepository.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepository.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/heart/service/HeartServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImplTest.java
Labels: 0-Low

#242 BE - 밸리데이션 추가 및 회원가입 중복여부 API 구현
  build.gradle
  src/main/java/com/zerobase/foodlier/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
  src/main/java/com/zerobase/foodlier/common/validator/image/ImageFile.java
  src/main/java/com/zerobase/foodlier/common/validator/image/ImageFileValidator.java
  src/main/java/com/zerobase/foodlier/global/auth/controller/AuthController.java
  src/main/java/com/zerobase/foodlier/global/point/controller/PointController.java
  src/main/java/com/zerobase/foodlier/global/profile/controller/ProfileController.java
  src/main/java/com/zerobase/foodlier/global/quotation/controller/QuotationController.java
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorController.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/MemberInputDto.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/PasswordFindForm.java
  src/main/java/com/zerobase/foodlier/module/member/member/dto/SignInForm.java
  src/main/java/com/zerobase/foodlier/module/member/member/profile/dto/MemberPrivateProfileForm.java
  src/main/java/com/zerobase/foodlier/module/member/member/profile/dto/PasswordChangeForm.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentRequest.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/quotation/QuotationDtoRequest.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDetailDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeDtoRequest.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeIngredientDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormDto.java
  src/main/java/com/zerobase/foodlier/module/review/chef/dto/ChefReviewForm.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/dto/RecipeReviewForm.java
  src/main/java/com/zerobase/foodlier/module/transaction/dto/SuggestionForm.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: 0-Low

#257 BE - 배치처리 사용으로 인한 채팅, 채팅방 비즈니스 로직 수정
  src/main/java/com/zerobase/foodlier/module/dm/room/domain/model/DmRoom.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/request/domain/model/Request.java
  src/test/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImplTest.java
Labels: 0-Low

#254 BE - 견적서 컨트롤러 테스트 코드 작성
  src/test/java/com/zerobase/foodlier/global/quotation/controller/QuotationControllerTest.java
  src/test/java/com/zerobase/foodlier/mockuser/WithCustomMockUser.java
  src/test/java/com/zerobase/foodlier/mockuser/WithCustomMockUserSecurityContextFactory.java
Labels: test

#253 BE - 소셜 로그인 테스트코드 작성
  src/main/java/com/zerobase/foodlier/module/member/member/client/KakaoApiClient.java
  src/main/java/com/zerobase/foodlier/module/member/member/client/NaverApiClient.java
  src/main/java/com/zerobase/foodlier/module/member/member/exception/OAuthErrorCode.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/KakaoInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/KakaoLoginParams.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/NaverInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/NaverLoginParams.java
  src/test/java/com/zerobase/foodlier/global/member/oAuth/facade/OAuthFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/OAuthInfoServiceImplTest.java
Labels: 0-Low, test

#255 BE - 레시피 페이지에서 조회 로직 오류 수정
  build.gradle
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/RecipeServiceImplTest.java
Labels: 2-High

#266 BE - Recipe Review 컨트롤러 테스트 코드
  src/test/java/com/zerobase/foodlier/global/review/controller/ReviewControllerTest.java
  src/test/resources/foodlier_logo.png
Labels: 0-Low

#275 FE - 레시피 사진 등록 가능하도록 수정
  frontend/src/components/recipe/RecipeImage.tsx
  frontend/src/pages/recipe/WriteRecipePage.tsx
  frontend/src/styles/recipe/RecipeImage.styled.ts
Labels: 3-Critical

#277 BE - 알림 기능 수정
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/ActionType.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/NotifyUrl.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/PerformerType.java
  src/main/java/com/zerobase/foodlier/common/aop/notification/type/SendType.java
  src/main/java/com/zerobase/foodlier/global/notification/facade/NotificationFacade.java
  src/main/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterServiceImpl.java
Labels: 3-Critical

#272 BE - point controller 테스트코드
  src/test/java/com/zerobase/foodlier/global/point/controller/PointControllerTest.java
Labels: test

#276 BE - RefrigeratorController 테스트 코드 작성
  src/test/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorControllerTest.java
Labels: test

#278 BE - 중복 확인 메서드에 대한 테스트 코드 작성
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: test

#281 BE - 검색 필터 수정
  src/main/java/com/zerobase/foodlier/common/elasticsearch/config/ElasticSearchConfig.java
  src/main/java/com/zerobase/foodlier/module/recipe/domain/document/RecipeDocument.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeSearchRequest.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeSearchCustomRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeSearchCustomRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeSearchRepository.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/OrderType.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/SearchType.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/SortType.java
  src/main/resources/elasticsearch/recipe-mapping.json
  src/test/java/com/zerobase/foodlier/global/comment/facade/comment/CommentFacadeTest.java
  src/test/java/com/zerobase/foodlier/global/notification/facade/NotificationFacadeTest.java
  src/test/java/com/zerobase/foodlier/global/quotation/controller/QuotationControllerTest.java
  src/test/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterServiceTest.java
  src/test/java/com/zerobase/foodlier/module/notification/service/notification/NotificationServiceTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/recipe/data/DummyDataGenerator.java
Labels: 1-Medium

#283 BE - HOTFIX 소셜로그인 시 소셜 서버에서 값을 받아오지 못하는 오류 수정
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/KakaoInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/NaverInfoResponse.java
Labels: 3-Critical

#285 BE - 검색 필터 기능 수정
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/heart/service/HeartServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/type/OrderType.java
  src/test/java/com/zerobase/foodlier/module/heart/service/HeartServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImplTest.java
Labels: 3-Critical

#286 BE - auth controller 테스트 코드 및 dto setter 추가
  src/main/java/com/zerobase/foodlier/module/member/member/dto/MemberInputDto.java
  src/main/java/com/zerobase/foodlier/module/member/member/profile/dto/MemberPrivateProfileForm.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/dto/RecipeReviewForm.java
  src/test/java/com/zerobase/foodlier/global/auth/controller/AuthControllerTest.java
Labels: 3-Critical, test

#282 BE - HOTFIX 결제 완료 redirect에서 cors 문제 해결
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
Labels: 3-Critical

#287 BE - 레시피 로직 리팩토링
  src/main/java/com/zerobase/foodlier/global/recipe/controller/RecipeController.java
  src/main/java/com/zerobase/foodlier/global/recipe/facade/RecipeFacade.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/recipe/facade/RecipeFacadeTest.java
Labels: 0-Low

#289 BE - project refactoring
  src/main/java/com/zerobase/foodlier/common/elasticsearch/config/ElasticSearchConfig.java
  src/main/java/com/zerobase/foodlier/common/redis/exception/EmailVerificationException.java
  src/main/java/com/zerobase/foodlier/common/redis/service/EmailVerificationServiceImpl.java
  src/main/java/com/zerobase/foodlier/common/response/ListResponse.java
  src/main/java/com/zerobase/foodlier/common/s3/service/S3Service.java
  src/main/java/com/zerobase/foodlier/common/s3/service/S3ServiceImpl.java
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
  src/main/java/com/zerobase/foodlier/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/foodlier/common/security/filter/JwtExceptionFilter.java
  src/main/java/com/zerobase/foodlier/common/security/provider/JwtTokenProvider.java
  src/main/java/com/zerobase/foodlier/common/websocket/config/AsyncConfig.java
  src/main/java/com/zerobase/foodlier/common/websocket/config/StompHandler.java
  src/main/java/com/zerobase/foodlier/global/comment/controller/CommentController.java
  src/main/java/com/zerobase/foodlier/global/comment/facade/comment/CommentFacade.java
  src/main/java/com/zerobase/foodlier/global/member/regiser/facade/MemberRegisterFacade.java
  src/main/java/com/zerobase/foodlier/global/notification/controller/NotificationController.java
  src/main/java/com/zerobase/foodlier/global/review/controller/ReviewController.java
  src/main/java/com/zerobase/foodlier/module/dm/dm/repository/DmRepository.java
  src/main/java/com/zerobase/foodlier/module/dm/room/exception/DmRoomErrorCode.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/heart/reposiotry/HeartRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/constants/ProfileUrlConstants.java
  src/main/java/com/zerobase/foodlier/module/member/member/local/service/LocalServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/KakaoInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/member/member/social/dto/NaverInfoResponse.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/NotificationDto.java
  src/main/java/com/zerobase/foodlier/module/notification/repository/notification/NotificationRepository.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponseHandleCancelDto.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponseHandleCardDto.java
  src/main/java/com/zerobase/foodlier/module/payment/dto/PaymentResponseHandleDto.java
  src/main/java/com/zerobase/foodlier/module/payment/repository/PaymentRepository.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/domain/document/RecipeDocument.java
  src/main/java/com/zerobase/foodlier/module/recipe/dto/recipe/RecipeCardDto.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImpl.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/notification/facade/NotificationFacadeTest.java
  src/test/java/com/zerobase/foodlier/global/refrigerator/controller/RefrigeratorControllerTest.java
  src/test/java/com/zerobase/foodlier/global/review/facade/ChefReviewFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/dm/dm/service/DmServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/local/service/LocalServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterServiceTest.java
  src/test/java/com/zerobase/foodlier/module/notification/service/notification/NotificationServiceTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/recipe/RecipeServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/recipe/service/recipe/data/DummyDataGenerator.java
  src/test/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceImplTest.java
Labels: 0-Low

#290 BE - 댓글과 답글 기능 수정
  src/main/java/com/zerobase/foodlier/global/comment/controller/CommentController.java
  src/main/java/com/zerobase/foodlier/global/profile/controller/ProfileController.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/dto/CommentDto.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/dto/MyPageCommentDto.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentRepository.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentSearchRepository.java
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentSearchRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/dto/ReplyDto.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplyRepository.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplySearchRepository.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplySearchRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyService.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/profile/controller/ProfileControllerTest.java
Labels: 1-Medium

#262 FE - 공통 요청 헤더 및 비밀번호 찾기 구현
  frontend/src/App.tsx
  frontend/src/constants/Styles.tsx
  frontend/src/main.tsx
  frontend/src/pages/auth/FindPasswordPage.tsx
  frontend/src/pages/auth/RegisterPage.tsx
  frontend/src/styles/auth/AuthModal.styled.ts
  frontend/src/styles/auth/LoginPage.styled.ts
  frontend/src/styles/auth/RegisterPage.styled.ts
  frontend/src/utils/FetchCall.tsx
Labels: 2-High

#291 BE - member refacotring
  src/main/java/com/zerobase/foodlier/global/profile/controller/ProfileController.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImpl.java
  src/test/java/com/zerobase/foodlier/global/profile/controller/ProfileControllerTest.java
  src/test/java/com/zerobase/foodlier/module/dm/room/service/DmRoomServiceImplTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceImplTest.java
Labels: 0-Low

#297 FE - 비밀번호 찾기, 소셜로그인 등
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/auth/FindPasswordPage.tsx
  frontend/src/pages/auth/KakaoRedirectionPage.tsx
  frontend/src/pages/auth/LoginPage.tsx
  frontend/src/pages/auth/NaverRedirectionPage.tsx
  frontend/src/pages/auth/RegisterPage.tsx
  frontend/src/services/authServices.tsx
  frontend/src/styles/auth/FindPasswordPage.styled.ts
  frontend/src/utils/FormValidation.tsx
Labels: 2-High

#295 BE - 댓글 및 답글 요청 테스트
  src/test/java/com/zerobase/foodlier/global/comment/controller/CommentControllerTest.java
Labels: test

#296 BE - 알림 정보 추가
  src/main/java/com/zerobase/foodlier/module/notification/domain/model/Notification.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/NotificationDto.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/notify/Impl/ChefNotify.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/notify/Impl/CommentNotify.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/notify/Impl/HeartNotify.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/notify/Impl/ReplyNotify.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/notify/Impl/RequesterNotify.java
  src/main/java/com/zerobase/foodlier/module/notification/dto/notify/Notify.java
  src/main/java/com/zerobase/foodlier/module/notification/repository/notification/NotificationRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/notification/service/notification/NotificationService.java
Labels: 3-Critical

#298 BE - Recipe에 대한 SoftDelete 정의 및 RequestForm 및 Request에 대한 누락 응답 칼럼 추가
  src/main/java/com/zerobase/foodlier/module/recipe/domain/model/Recipe.java
  src/main/java/com/zerobase/foodlier/module/request/dto/RequestDetailDto.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestService.java
  src/main/java/com/zerobase/foodlier/module/requestform/dto/RequestFormDetailDto.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormService.java
  src/test/java/com/zerobase/foodlier/module/request/service/RequestServiceTest.java
  src/test/java/com/zerobase/foodlier/module/requestForm/service/RequestFormServiceTest.java
Labels: 0-Low

#299 BE - RecipeController 테스트코드 작성
  src/test/java/com/zerobase/foodlier/global/recipe/controller/RecipeControllerTest.java
Labels: 0-Low, test

#302 BE - queryDSL
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentSearchRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplySearchRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/dm/room/repository/DmRoomRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/member/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/notification/repository/notification/NotificationRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/recipe/repository/RecipeRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepositoryCustomImpl.java
Labels: 0-Low

#303 BE - 알림 요청 테스트
  src/test/java/com/zerobase/foodlier/global/notification/controller/NotificationControllerTest.java
Labels: 1-Medium

#304 BE - DmController, StompChatController 테스트코드 작성
  src/main/java/com/zerobase/foodlier/global/dm/controller/StompChatController.java
  src/test/java/com/zerobase/foodlier/global/dm/controller/DmControllerTest.java
  src/test/java/com/zerobase/foodlier/global/dm/controller/StompChatControllerTest.java
Labels: 0-Low, test

#305 BE - !HOTFIX 공개 프로필 RecipeReview 조회 쿼리 수정
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepository.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepositoryCustom.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/repository/RecipeReviewRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewService.java
  src/test/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewServiceTest.java
Labels: bug

#306 BE - 알림 전송 객체 관련 에러 처리
  src/main/java/com/zerobase/foodlier/module/notification/service/emitter/EmitterService.java
Labels: bug

#311 FE - 5주차 작업
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Notification.tsx
  frontend/src/components/SideNotification.tsx
  frontend/src/components/auth/CommentItem.tsx
  frontend/src/components/notification/NotificationItem.tsx
  frontend/src/components/recipe/RecipeImage.tsx
  frontend/src/components/recipe/RecipeItem.tsx
  frontend/src/components/recipe/detail/DetailEditDelete.tsx
  frontend/src/components/recipe/detail/DetailMain.tsx
  frontend/src/components/refrigerator/SearchRecipeModal.tsx
  frontend/src/components/search/MoSearch.tsx
  frontend/src/components/search/SearchBar.tsx
  frontend/src/components/search/WebSearch.tsx
  frontend/src/components/slider/Slider.tsx
  frontend/src/components/slider/SliderCard.tsx
  frontend/src/constants/Data.tsx
  frontend/src/constants/Interfaces.tsx
  frontend/src/constants/Styles.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NotFoundPage.tsx
  frontend/src/pages/recipe/RecipeDetailPage.tsx
  frontend/src/pages/recipe/RecipePage.tsx
  frontend/src/pages/recipe/WriteRecipePage.tsx
  frontend/src/pages/refrigerator/RequestDetailPage.tsx
  frontend/src/pages/refrigerator/WriteRequestPage.tsx
  frontend/src/pages/user/MyLogPage.tsx
  frontend/src/pages/user/MyPage.tsx
  frontend/src/services/authServices.tsx
  frontend/src/styles/BottomNavigation.styled.ts
  frontend/src/styles/Header.styled.ts
  frontend/src/styles/MainPage.styled.ts
  frontend/src/styles/NotFoundPage.styled.ts
  frontend/src/styles/auth/CommentItem.styled.ts
  frontend/src/styles/auth/FindPasswordPage.styled.ts
  frontend/src/styles/auth/LoginPage.styled.ts
  frontend/src/styles/auth/RegisterPage.styled.ts
  frontend/src/styles/recipe/EmptyRecipeItem.styled.ts
  frontend/src/styles/recipe/RecipeImage.styled.ts
  frontend/src/styles/recipe/RecipeItem.styled.ts
  frontend/src/styles/recipe/RecipePage.styled.ts
  frontend/src/styles/recipe/WriteRecipePage.styled.ts
  frontend/src/styles/recipe/detail/DetailEditDelete.styled.ts
  frontend/src/styles/refrigerator/CookForMe.styled.ts
  frontend/src/styles/refrigerator/CookForYou.styled.ts
  frontend/src/styles/refrigerator/ListModal.styled.ts
  frontend/src/styles/refrigerator/QuotationDetailPage.styled.ts
  frontend/src/styles/refrigerator/RequestDetailPage.styled.ts
  frontend/src/styles/refrigerator/SearchRecipeModal.styled.ts
  frontend/src/styles/search/SearchBar.styled.ts
  frontend/src/styles/slider/SliderCard.styled.ts
  frontend/src/styles/ui/CustomSelect.styled.ts
  frontend/src/styles/ui/SideNotification.styled.ts
  frontend/src/styles/user/MyLogPage.styled.ts
  frontend/src/utils/FetchCall.tsx
Labels: 2-High

#308 BE - HOTFIX 레시피 수정시 수정된 레시피의 이미지가 기존의 이미지라면 삭제하지 않게 수정
  src/main/java/com/zerobase/foodlier/global/recipe/facade/RecipeFacade.java
Labels: 3-Critical

#309 BE - project refactoring
  src/main/java/com/zerobase/foodlier/common/redis/service/EmailVerificationService.java
  src/main/java/com/zerobase/foodlier/common/redis/service/EmailVerificationServiceImpl.java
  src/main/java/com/zerobase/foodlier/common/redis/service/RefreshTokenService.java
  src/main/java/com/zerobase/foodlier/common/redis/service/RefreshTokenServiceImpl.java
  src/main/java/com/zerobase/foodlier/common/redisson/service/RedissonLockService.java
  src/main/java/com/zerobase/foodlier/common/redisson/service/RedissonLockServiceImpl.java
  src/main/java/com/zerobase/foodlier/common/s3/service/S3Service.java
  src/main/java/com/zerobase/foodlier/common/s3/service/S3ServiceImpl.java
  src/test/java/com/zerobase/foodlier/common/redis/service/EmailVerificationServiceTest.java
  src/test/java/com/zerobase/foodlier/common/redisson/service/RedissonLockServiceTest.java
  src/test/java/com/zerobase/foodlier/common/s3/service/S3ServiceTest.java
  src/test/java/com/zerobase/foodlier/global/dm/controller/DmControllerTest.java
Labels: 0-Low

#310 BE - 서비스 계층 transactional 어노테이션 추가
  src/main/java/com/zerobase/foodlier/module/comment/comment/service/CommentService.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/servcie/ReplyService.java
  src/main/java/com/zerobase/foodlier/module/dm/dm/service/DmService.java
  src/main/java/com/zerobase/foodlier/module/dm/room/service/DmRoomService.java
  src/main/java/com/zerobase/foodlier/module/history/charge/service/PointChargeHistoryService.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryService.java
  src/main/java/com/zerobase/foodlier/module/member/chef/service/ChefMemberService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/payment/service/PaymentService.java
  src/main/java/com/zerobase/foodlier/module/recipe/service/quotation/QuotationService.java
  src/main/java/com/zerobase/foodlier/module/request/service/RequestService.java
  src/main/java/com/zerobase/foodlier/module/requestform/service/RequestFormService.java
  src/main/java/com/zerobase/foodlier/module/review/chef/service/ChefReviewService.java
  src/main/java/com/zerobase/foodlier/module/review/recipe/service/RecipeReviewService.java
  src/main/java/com/zerobase/foodlier/module/transaction/service/TransactionService.java
Labels: 0-Low

#314 BE - !hotfix 알림 목록 조회 쿼리 수정
  src/main/java/com/zerobase/foodlier/module/notification/repository/notification/NotificationRepositoryCustomImpl.java
Labels: 3-Critical

#319 FE - 로그인 및 쿠키 누락된 코드 추가
  .gitignore
  frontend/src/components/BottomNavigation.tsx
  frontend/src/pages/auth/LoginPage.tsx
  frontend/src/pages/user/MyPage.tsx
  frontend/src/utils/FetchCall.tsx
Labels: 3-Critical

#320 BE - 커밋에서 잘못 반영된 내용 수정/삭제
  src/main/generated/com/zerobase/foodlier/common/jpa/audit/QAudit.java
  src/main/generated/com/zerobase/foodlier/module/comment/comment/domain/model/QComment.java
  src/main/generated/com/zerobase/foodlier/module/comment/reply/domain/model/QReply.java
  src/main/generated/com/zerobase/foodlier/module/dm/dm/domain/model/QDm.java
  src/main/generated/com/zerobase/foodlier/module/dm/room/domain/model/QDmRoom.java
  src/main/generated/com/zerobase/foodlier/module/dm/room/domain/vo/QSuggestion.java
  src/main/generated/com/zerobase/foodlier/module/heart/domain/model/QHeart.java
  src/main/generated/com/zerobase/foodlier/module/history/charge/domain/model/QPointChargeHistory.java
  src/main/generated/com/zerobase/foodlier/module/history/transaction/domain/model/QMemberBalanceHistory.java
  src/main/generated/com/zerobase/foodlier/module/member/chef/domain/model/QChefMember.java
  src/main/generated/com/zerobase/foodlier/module/member/member/domain/model/QMember.java
  src/main/generated/com/zerobase/foodlier/module/member/member/domain/vo/QAddress.java
  src/main/generated/com/zerobase/foodlier/module/notification/domain/model/QNotification.java
  src/main/generated/com/zerobase/foodlier/module/payment/domain/model/QPayment.java
  src/main/generated/com/zerobase/foodlier/module/recipe/domain/model/QRecipe.java
  src/main/generated/com/zerobase/foodlier/module/recipe/domain/vo/QRecipeDetail.java
  src/main/generated/com/zerobase/foodlier/module/recipe/domain/vo/QRecipeIngredient.java
  src/main/generated/com/zerobase/foodlier/module/recipe/domain/vo/QRecipeStatistics.java
  src/main/generated/com/zerobase/foodlier/module/recipe/domain/vo/QSummary.java
  src/main/generated/com/zerobase/foodlier/module/request/domain/model/QRequest.java
  src/main/generated/com/zerobase/foodlier/module/request/domain/vo/QIngredient.java
  src/main/generated/com/zerobase/foodlier/module/requestform/domain/model/QRequestForm.java
  src/main/generated/com/zerobase/foodlier/module/review/chef/domain/model/QChefReview.java
  src/main/generated/com/zerobase/foodlier/module/review/recipe/domain/model/QRecipeReview.java
  src/main/java/com/zerobase/foodlier/common/elasticsearch/config/ElasticSearchConfig.java
Labels: 3-Critical

#322 BE - !HOTFIX: 가격제안 valid 수정
  src/main/java/com/zerobase/foodlier/module/transaction/service/TransactionService.java
Labels: 3-Critical

#323 BE - 메일 전송시 HTML 템플릿 적용
  src/main/java/com/zerobase/foodlier/module/member/member/mail/constants/MailConstants.java
  src/main/java/com/zerobase/foodlier/module/member/member/mail/exception/MailErrorCode.java
  src/main/java/com/zerobase/foodlier/module/member/member/mail/exception/MailException.java
  src/main/java/com/zerobase/foodlier/module/member/member/mail/service/MailServiceImpl.java
  src/test/java/com/zerobase/foodlier/module/member/member/mail/service/MailServiceImplTest.java
Labels: 0-Low

#324 BE - !hotfix 댓글 및 대댓글 목록 조회 수정
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentSearchRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplySearchRepositoryImpl.java
Labels: 3-Critical

#326 BE - !hotfix 댓글 count 쿼리 및 join 조건 수정
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentSearchRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplySearchRepositoryImpl.java
Labels: 3-Critical

#328 BE - !HOTFIX lock
  src/main/java/com/zerobase/foodlier/common/aop/RedissonLock.java
  src/main/java/com/zerobase/foodlier/common/redisson/service/RedissonLockAop.java
  src/main/java/com/zerobase/foodlier/common/redisson/service/RedissonLockService.java
  src/test/java/com/zerobase/foodlier/common/redisson/service/RedissonLockAopTest.java
  src/test/java/com/zerobase/foodlier/common/redisson/service/RedissonLockServiceTest.java
  src/test/java/com/zerobase/foodlier/module/transaction/service/TransactionServiceTest.java
Labels: 3-Critical

#330 BE - !hotfix: 조인 조건 수정
  src/main/java/com/zerobase/foodlier/module/comment/comment/repository/CommentSearchRepositoryImpl.java
  src/main/java/com/zerobase/foodlier/module/comment/reply/reposiotry/ReplySearchRepositoryImpl.java
Labels: 3-Critical

#331 BE - project fix & refactoring
  src/main/java/com/zerobase/foodlier/global/profile/controller/ProfileController.java
  src/main/java/com/zerobase/foodlier/global/profile/facade/ProfileFacade.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/domain/model/MemberBalanceHistory.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/dto/MemberBalanceHistoryDto.java
  src/main/java/com/zerobase/foodlier/module/history/transaction/service/MemberBalanceHistoryService.java
  src/main/java/com/zerobase/foodlier/module/member/member/service/MemberService.java
  src/main/java/com/zerobase/foodlier/module/transaction/dto/TransactionDto.java
  src/main/java/com/zerobase/foodlier/module/transaction/service/TransactionService.java
  src/test/java/com/zerobase/foodlier/global/profile/controller/ProfileControllerTest.java
  src/test/java/com/zerobase/foodlier/global/profile/facade/ProfileFacadeTest.java
  src/test/java/com/zerobase/foodlier/module/member/member/service/MemberServiceTest.java
Labels: 3-Critical

#334 BE - !hotfix 알림 전송 기능 비동기 통신 방식으로 수정
  src/main/java/com/zerobase/foodlier/FoodlierApplication.java
  src/main/java/com/zerobase/foodlier/global/notification/facade/NotificationFacade.java
Labels: 3-Critical

#338 BE - !hotfix: 알림 목록 페이징 수정
  src/main/java/com/zerobase/foodlier/module/notification/repository/notification/NotificationRepositoryCustomImpl.java
  src/main/java/com/zerobase/foodlier/module/notification/service/notification/NotificationService.java
Labels: 3-Critical

#339 BE - profile facade 단에 transactional 추가
  src/main/java/com/zerobase/foodlier/global/profile/facade/ProfileFacade.java
Labels: 3-Critical

#340 FE - 댓글, 후기 API 연동
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/Notification.tsx
  frontend/src/components/notification/NotificationItem.tsx
  frontend/src/components/recipe/detail/DetailEditDelete.tsx
  frontend/src/components/recipe/detail/comment/RecipeComment.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewItem.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewList.tsx
  frontend/src/components/refrigerator/ChefCard.tsx
  frontend/src/components/refrigerator/CookForYou.tsx
  frontend/src/components/refrigerator/QuotationItem.tsx
  frontend/src/components/refrigerator/RequestItem.tsx
  frontend/src/components/refrigerator/SearchRecipeModal.tsx
  frontend/src/components/user/UserChefInfo.tsx
  frontend/src/constants/Interfaces.tsx
  frontend/src/constants/Styles.tsx
  frontend/src/pages/chat/DmTest2.tsx
  frontend/src/pages/recipe/RecipeDetailPage.tsx
  frontend/src/pages/recipe/RecipePage.tsx
  frontend/src/pages/recipe/WriteRecipePage.tsx
  frontend/src/pages/recipe/WriteReviewPage.tsx
  frontend/src/pages/refrigerator/RequestDetailPage.tsx
  frontend/src/pages/refrigerator/WriteQuotationPage.tsx
  frontend/src/pages/refrigerator/WriteRequestPage.tsx
  frontend/src/styles/Header.styled.ts
  frontend/src/styles/MainPage.styled.ts
  frontend/src/styles/auth/CommentItem.styled.ts
  frontend/src/styles/chat/ChattingPage.styled.ts
  frontend/src/styles/chat/ProposalModal.styled.ts
  frontend/src/styles/point/DealModal.styled.ts
  frontend/src/styles/recipe/EmptyRecipeItem.styled.ts
  frontend/src/styles/recipe/RecipeItem.styled.ts
  frontend/src/styles/recipe/RecipePage.styled.ts
  frontend/src/styles/recipe/WriteRecipePage.styled.ts
  frontend/src/styles/recipe/WriteReviewPage.styled.ts
  frontend/src/styles/recipe/detail/DetailEditDelete.styled.ts
  frontend/src/styles/recipe/detail/DetailMain.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeComment.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentForm.styled.ts
  frontend/src/styles/recipe/detail/comment/RecipeCommentItem.styled.ts
  frontend/src/styles/recipe/detail/review/RecipeReviewItem.styled.ts
  frontend/src/styles/refrigerator/ChefCard.styled.ts
  frontend/src/styles/refrigerator/CookForMe.styled.ts
  frontend/src/styles/refrigerator/CookForYou.styled.ts
  frontend/src/styles/refrigerator/ListModal.styled.ts
  frontend/src/styles/refrigerator/QuotationDetailPage.styled.ts
  frontend/src/styles/refrigerator/QuotationItem.styled.ts
  frontend/src/styles/refrigerator/RefrigeratorMap.styled.ts
  frontend/src/styles/refrigerator/RequestDetailPage.styled.ts
  frontend/src/styles/refrigerator/WriteQuotationPage.styled.ts
  frontend/src/styles/refrigerator/WriteRequestPage.styled.ts
  frontend/src/styles/search/SearchBar.styled.ts
  frontend/src/styles/ui/CustomSelect.styled.ts
  frontend/src/styles/ui/SideNotification.styled.ts
  frontend/src/styles/user/MyPage.styled.ts
  frontend/src/styles/user/ProfilePage.styled.ts
  frontend/src/styles/user/UserReviewedItem.styled.ts
  frontend/src/utils/FetchCall.tsx
  frontend/vite.config.ts
Labels: 2-High

#341 BE - !hotfix: cors 해결을 위한 주소 추가
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
Labels: 3-Critical

#343 FE - 기타 기능 구현 (알림, 내 정보 수정, 비밀번호 찾기 등)
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Notification.tsx
  frontend/src/components/auth/AddressModal.tsx
  frontend/src/components/chef/ChefItem.tsx
  frontend/src/components/notification/NotificationItem.tsx
  frontend/src/components/recipe/detail/DetailMain.tsx
  frontend/src/components/recipe/detail/comment/RecipeComment.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewItem.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewList.tsx
  frontend/src/constants/Interfaces.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/user/EditPasswordPage.tsx
  frontend/src/pages/user/MyPage.tsx
  frontend/src/pages/user/ProfileEditPage.tsx
  frontend/src/services/authServices.tsx
  frontend/src/styles/chef/ChefItem.styled.ts
  frontend/src/styles/user/EditPasswordPage.styled.ts
  frontend/src/styles/user/ProfileEdit.styled.ts
  frontend/src/utils/FetchCall.tsx
  frontend/src/utils/returnDate.tsx
Labels: 2-High

#344 FE - 채팅방 모바일 버전 UI 수정 작업 하였습니다.
  frontend/src/pages/point/TradeHistoryPage.tsx
  frontend/src/styles/chat/ChatRoom.styled.ts
Labels: 1-Medium

#350 BE - cors test
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
  src/main/java/com/zerobase/foodlier/common/security/config/WebMvcConfig.java
Labels: 3-Critical

#351 BE - !HOTFIX recipeCount를 가져오는 QueryDSL 수정.
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepositoryCustomImpl.java
Labels: bug

#352 BE - cors test
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
Labels: bug

#360 BE - !hotfix: cors 해결
  src/main/java/com/zerobase/foodlier/common/security/config/SecurityConfig.java
Labels: 3-Critical

#365 BE - !HOTFIX 요청한 요리사 조회 부분 수정 Query 수정.
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepositoryCustomImpl.java
Labels: bug

#373 BE - !HOTFIX 주변 요리사 조회 recipeCount 정렬 오류 수정
  src/main/java/com/zerobase/foodlier/module/member/chef/repository/ChefMemberRepositoryCustomImpl.java
Labels: bug

#372 FE - 전반적인 버그 및 수정 작업
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/ProposalModal.tsx
  frontend/src/components/point/DealModal.tsx
  frontend/src/components/point/RejectModal.tsx
  frontend/src/components/user/UserChefInfo.tsx
  frontend/src/pages/chat/ChattingPage.tsx
  frontend/src/pages/point/PointPage.tsx
  frontend/src/pages/user/MyPage.tsx
  frontend/src/pages/user/ProfilePage.tsx
  frontend/src/styles/user/UserChefInfo.styled.ts
Labels: bug

#374 FE - 메인 페이지 좋아요 기능 추가
  frontend/src/App.tsx
  frontend/src/components/recipe/RecipeImage.tsx
  frontend/src/components/slider/SliderCard.tsx
  frontend/src/pages/recipe/WriteRecipePage.tsx
  frontend/src/pages/refrigerator/WriteRequestPage.tsx
  frontend/src/styles/slider/SliderCard.styled.ts
Labels: bug, 3-Critical

#375 BE - 미열람 알림 조회 수정
  src/main/java/com/zerobase/foodlier/module/notification/repository/notification/NotificationRepositoryCustomImpl.java
Labels: 0-Low

#376 FE : 댓글 작성자 프로필 연결, 후기 작성하기 버튼 navigate 수정
  frontend/src/components/recipe/detail/comment/RecipeComment.tsx
  frontend/src/components/recipe/detail/review/RecipeReviewItem.tsx
  frontend/src/pages/recipe/WriteRecipePage.tsx
  frontend/src/pages/recipe/WriteReviewPage.tsx
  frontend/src/pages/refrigerator/WriteRequestPage.tsx
  frontend/src/styles/MainPage.styled.ts
  frontend/src/styles/chef/ChefItem.styled.ts
  frontend/src/styles/recipe/WriteRecipePage.styled.ts
  frontend/src/styles/recipe/detail/DetailMain.styled.ts
  frontend/src/styles/refrigerator/WriteRequestPage.styled.ts
  frontend/src/styles/ui/SideNotification.styled.ts
  frontend/src/styles/user/EditPasswordPage.styled.ts
  frontend/src/styles/user/ProfileEdit.styled.ts
Labels: bug

#379 BE - 회원 정보 수정 s3 사진 삭제 조건 수정
  src/main/java/com/zerobase/foodlier/global/profile/facade/ProfileFacade.java
Labels: bug

#383 BE - 소셜 로그인 시 token 생성할 때 값을 못가져오는 오류 수정
  src/main/java/com/zerobase/foodlier/global/member/oAuth/facade/OAuthFacade.java
Labels: bug

#384 FE - 네이버, 카카오 로그인 안되는 이슈 해결
  frontend/src/pages/auth/KakaoRedirectionPage.tsx
  frontend/src/pages/auth/LoginPage.tsx
  frontend/src/pages/auth/NaverRedirectionPage.tsx
  frontend/src/services/authServices.tsx
Labels: bug
